- Infrastructure:
    - GitHub:
        - abbr: GH
          href: https://github.com/
    - Docker Hub:
        - abbr: DH
          href: https://hub.docker.com/

- Documentation:
    - Homepage Docs:
        - abbr: HP
          href: https://gethomepage.dev/
    - HTMX Docs:
        - abbr: HX
          href: https://htmx.org/docs/
    - Gin Web Framework:
        - abbr: GIN
          href: https://gin-gonic.com/docs/
